### ISSUE TITLE
free Introduction to Algorithms

### ISSUE THREAD

**Issue by mpullano** [btholt/four-semesters-of-cs#11]
Dear Brian, I'm the textbook manager at the MIT Press, and I received a query from a customer looking for the free edition of Introduction to Algorithms that you mention [here](http://btholt.github.io/four-semesters-of-cs/https://mitpress.mit.edu/books/introduction-algorithms).  This book is not freely available within copyright. Can you revise your wording so we don't frustrate readers by leading them to believe that this book is freely available? Thank you for your support of Introduction to Algorithms. Michelle Pullano, Textbook Manager, the MIT Press, mpullano@mit.edu

**Comment by btholt** [comment]
Fixed. Very sorry about the confusion.
