### ISSUE TITLE
Jasmine doesn't work in Codepen

### ISSUE THREAD

**Issue by jorgearuv** [btholt/four-semesters-of-cs#33]
For the factorial exercise, the output just displays `1 spec, 0 failures, 1 pending spec` and it doesn't change. Might be due to a breaking change from Jasmine.

https://codepen.io/btholt/pen/QyMjNa?editors=0011

**Comment by haticecs** [comment]
@jorgeruvalcaba 
When you add the function it works.
https://codepen.io/haticecs/pen/yLMbEqy

**Comment by jorgearuv** [comment]
You're right @haticecs, thank you!
